"""
Definitions for supported departments
"""
from dataclasses import dataclass, field
from ... import route


@dataclass(frozen=True)
class DeptConfig:
    name: str
    wd_ids: list = field(default_factory=list)


DEPT_CONFIG = {
    route.ACUPUNCTURE: DeptConfig("Acupuncture", ["CC_72045"]),
    route.BEHAVIORAL_HEALTH: DeptConfig("Palouse Psychiatry and Behavioral Health", ["CC_72760"]),
    route.BIRTHPLACE: DeptConfig("Birthplace", ["CC_60790"]),
    route.CARDIO_PULM_REHAB: DeptConfig("Cardiopulmonary Rehabilitation", ["CC_71850"]),
    route.CARDIOLOGY: DeptConfig("Palouse Heart Center", ["CC_72790"]),
    route.ED: DeptConfig("Emergency", ["CC_72300", "CC_72390"]),
    route.FAMILY_MED: DeptConfig("Pullman Family Medicine", ["CC_72770"]),
    route.GENETICS: DeptConfig("Genetic Counseling", ["CC_72055"]),
    route.HOSPITALIST: DeptConfig("Hospitalist", ["CC_60150"]),
    route.ICU: DeptConfig("ICU", ["CC_60100"]),
    route.IMAGING: DeptConfig(
        "Imaging",
        [
            "CC_71300",  # CT
            "CC_71200",  # MRI
            "CC_71400",  # Imaging Services
            "CC_71430",  # Ultrasound
            "CC_71600",  # NM / PET
            "CC_71450",  # Mammography
        ],
    ),
    route.LAB: DeptConfig("Laboratory", ["CC_70700"]),
    route.MASSAGE: DeptConfig("Massage Therapy", ["CC_72025"]),
    route.MSU: DeptConfig("Medical Surgical Unit", ["CC_60700"]),
    route.NUTRITION: DeptConfig("Nutrition Therapy", ["CC_83210"]),
    route.PEDIATRICS: DeptConfig("Palouse Pediatrics", ["CC_72745", "CC_72740"]),
    route.PHARMACY: DeptConfig("Pharmacy", ["CC_71700"]),
    route.PODIATRY: DeptConfig("Pullman Foot and Ankle Clinic", ["CC_72720"]),
    route.REDSAGE: DeptConfig("Red Sage", ["CC_83200"]),
    route.REHAB: DeptConfig("Rehabilitation Services", ["CC_72000"]),
    route.RESIDENCY: DeptConfig("Family Medicine Residency", ["CC_74910"]),
    route.RESPIRATORY: DeptConfig("Respiratory Care Services", ["CC_71800"]),
    route.SAME_DAY: DeptConfig("Same Day Services", ["CC_70260"]),
    route.SLEEP: DeptConfig("Palouse Sleep Medicine and Pulmonology", ["CC_72785", "CC_71810"]),
    route.SUMMIT: DeptConfig("Summit", ["CC_72045", "CC_72055", "CC_72025", "CC_72015"]),
    route.SURGERY: DeptConfig("Surgery", ["CC_70200", "CC_72780"]),
    route.UROLOGY: DeptConfig("Palouse Urology", ["CC_72750"]),
}


def config_from_route(route_id: str):
    """
    Return the configuration for a given department by route_id.
    route_id is generated by route.route_by_query() based on the "dept" URL query param.
    """
    return DEPT_CONFIG.get(route_id, None)
